spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://userservicepostgres:5439/userservicepostgres
    username: root
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase-changelog.xml
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://userservicepostgres:5439/userservicepostgres
    user: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none


server:
  port: 8081